language: objective-c
osx_image: xcode7.2
install:
- gem install jazzy --no-rdoc --no-ri --no-document
notifications:
  email:
  - john.daub@ovenbits.com
  - jonathan.landon@ovenbits.com
  - ben.kreeger@ovenbits.com
script:
- xcodebuild -project Alexandria.xcodeproj -scheme Alexandria -sdk iphonesimulator9.2
  -destination 'platform=iOS Simulator,name=iPhone 6,OS=9.2' test
after_success:
- ./Support/create_docs.sh
env:
  global:
    secure: kIYrXNlCcYqQrnWoOBReN3iQj9fAGvevhalLwo569MAXo7o0eAsmhNpYb906zwclO5aPoNsK3NXxsDrNDJlCtcbd25hLowPcEI9g77Tc6SzU/bFJbbfXkecHjByiZrVXr8HqwkzvbQ/kvSLTIysK4Q49OEHaU1g309kqPdCW6GRye+3IWxrFgmvH55AoCxQDyUF29JZvjIrP1QcJpbnbZM9vSd3eoc317MD7vGaifA/NX9EsqT6v4q9TyVvMOwsFcnBOmmzKI9bU88vewbVxEdy2zRRiJIxKRaxCcYTQ0q6Jvm5Fxm0e2bAa/kh5ThQ2YA37ap/j6zfSvwFVaOrAa3M9JBW804+jsbc2TrwXBAtbscwQuyhOIRNS9vM+DuROkXw28TvvQh8dnz5na3KJO1dezTtD/ZXz2Kngz6fV1EvwQseBNKmSAz3FFQEsTLkS2tWsrtFv+BTcSQ79ThW5LuzfZsfvY61xBREt5zdvgPK8zMAzIdE2IcpFW0J4iQTJ2bmMdzOd3rwARVoXjDjPxr6vi1hSLS0naxFDL0Oku1kgdGXYL4lyOqRqibcjzLQb+m4uelBH30hxkxSRabfQNIS6K10oPzowN3OvZGmvHduwt5qC5wT24AwoPod+gcjtqfYC7Xo+RQWpLBQV6SM0BkDocGEHBe50A2EUfZqukyQ=
