language: objective-c
osx_image: xcode7.2
notifications:
  email: 
    - john.daub@ovenbits.com
    - jonathan.landon@ovenbits.com
    - ben.kreeger@ovenbits.com
script:
    - xcodebuild -project Alexandria.xcodeproj -scheme Alexandria -sdk iphonesimulator9.2 -destination 'platform=iOS Simulator,name=iPhone 6,OS=9.2' test
    